require File.expand_path('../boot', __FILE__)

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Scholarspace
  class Application < Rails::Application
    
    config.generators do |g|
      g.test_framework :rspec, :spec => true
    end


    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de

    config.gw_affiliations = {
      "Accountancy" => "Accountancy",
      "Advocacy in the Global Environment" => "Advocacy in the Global Environment",
      "Africana Studies" => "Africana Studies",
      "American Studies" => "American Studies",
      "Anatomy & Regenerative Biology" => "Anatomy & Regenerative Biology",
      "Anesthesiology & Critical Care Medicine" => "Anesthesiology & Critical Care Medicine",
      "Anthropology" => "Anthropology",
      "Art Therapy" => "Art Therapy",
      "Asian Studies" => "Asian Studies",
      "Biochemistry & Molecular Medicine" => "Biochemistry & Molecular Medicine",
      "Bioinformatics" => "Bioinformatics",
      "Biological Sciences" => "Biological Sciences",
      "Biomedical Engineering" => "Biomedical Engineering",
      "Business & Finance Law " => "Business & Finance Law ",
      "Chemistry" => "Chemistry",
      "Civil & Environmental Engineering" => "Civil & Environmental Engineering",
      "Classical & Near Eastern Languages & Civilizations" => "Classical & Near Eastern Languages & Civilizations",
      "Classical Acting" => "Classical Acting",
      "Clinical Research & Leadership" => "Clinical Research & Leadership",
      "Cocoran Arts & Humanities" => "Cocoran Arts & Humanities",
      "Cocoran Graphic Design" => "Cocoran Graphic Design",
      "Computer Science" => "Computer Science",
      "Corcoran Art and the Book" => "Corcoran Art and the Book",
      "Corcoran Art Education" => "Corcoran Art Education",
      "Corcoran Digital Media Design" => "Corcoran Digital Media Design",
      "Corcoran Exhibition Design" => "Corcoran Exhibition Design",
      "Corcoran Fine Art" => "Corcoran Fine Art",
      "Corcoran Fine Art Photography" => "Corcoran Fine Art Photography",
      "Corcoran Interior Architecture and Design" => "Corcoran Interior Architecture and Design",
      "Corcoran New Media Photojournalism" => "Corcoran New Media Photojournalism",
      "Corcoran Photojournalism" => "Corcoran Photojournalism",
      "Biostatistics Center" => "Biostatistics Center",
      "Corcoran School of the Arts and Design" => "Corcoran School of the Arts and Design",
      "Counseling & Human Development" => "Counseling & Human Development",
      "Curriculum & Pedagogy" => "Curriculum & Pedagogy",
      "Cybersecurity, Strategy, and Information Management" => "Cybersecurity, Strategy, and Information Management",
      "Decision Studies" => "Decision Studies",
      "Dermatology" => "Dermatology",
      "East Asian Languages & Literatures" => "East Asian Languages & Literatures",
      "Economics" => "Economics",
      "Educational Leadership" => "Educational Leadership",
      "Electrical & Computer Engineerin" => "Electrical & Computer Engineerin",
      "Emergency Medicine" => "Emergency Medicine",
      "Engineering Management & Systems Engineering" => "Engineering Management & Systems Engineering",
      "English" => "English",
      "Environmental & Energy Law" => "Environmental & Energy Law",
      "Environmental & Occupational Health" => "Environmental & Occupational Health",
      "Environmental Resource Policy" => "Environmental Resource Policy",
      "Environmental Studies" => "Environmental Studies",
      "Epidemiology & Biostatistics" => "Epidemiology & Biostatistics",
      "European and Eurasian Studies" => "European and Eurasian Studies",
      "Exercise & Nutrition Sciences" => "Exercise & Nutrition Sciences",
      "Film Studies" => "Film Studies",
      "Finance" => "Finance",
      "Fine Arts & Art History" => "Fine Arts & Art History",
      "Forensic Psychology" => "Forensic Psychology",
      "Forensic Sciences" => "Forensic Sciences",
      "Geography" => "Geography",
      "Geological Sciences" => "Geological Sciences",
      "Global Communication" => "Global Communication",
      "Global Health" => "Global Health",
      "Government Procurement Law" => "Government Procurement Law",
      "Graduate School of Political Management" => "Graduate School of Political Management",
      "Health Policy & Management" => "Health Policy & Management",
      "History" => "History",
      "Human Services & Social Justice" => "Human Services & Social Justice",
      "Information Systems & Technology Management" => "Information Systems & Technology Management",
      "Integrated Information, Security, and Technology" => "Integrated Information, Security, and Technology",
      "Integrative Systems Biology" => "Integrative Systems Biology",
      "Intellectual Property Law" => "Intellectual Property Law",
      "Interior Architecture & Design" => "Interior Architecture & Design",
      "International & Comparitive Law" => "International & Comparitive Law",
      "International Affairs" => "International Affairs",
      "International Business" => "International Business",
      "International Development Studies" => "International Development Studies",
      "International Science and Technology Policy" => "International Science and Technology Policy",
      "International Trade and Investment Policy" => "International Trade and Investment Policy",
      "Journalism & Mass Communication" => "Journalism & Mass Communication",
      "Judaic Studies" => "Judaic Studies",
      "Landscape Design" => "Landscape Design",
      "Latin American and Hemispheric Studies" => "Latin American and Hemispheric Studies",
      "Law Firm Management" => "Law Firm Management",
      "Legislative Affairs" => "Legislative Affairs",
      "LGBT Health" => "LGBT Health",
      "Libraries" => "Libraries",
      "Linguistics" => "Linguistics",
      "Litigation & Dispute Resolution" => "Litigation & Dispute Resolution",
      "Management" => "Management",
      "Marketing" => "Marketing",
      "Mathematics" => "Mathematics",
      "Mechanical & Aerospace Engineering" => "Mechanical & Aerospace Engineering",
      "Media and Strategic Communication" => "Media and Strategic Communication",
      "Medicine" => "Medicine",
      "Microbiology, Immunology, & Tropical Medicine" => "Microbiology, Immunology, & Tropical Medicine",
      "Middle East Studies" => "Middle East Studies",
      "Museum Studies" => "Museum Studies",
      "Music" => "Music",
      "National Security & U.S. Foreign Relations Law" => "National Security & U.S. Foreign Relations Law",
      "Neurological Surgery" => "Neurological Surgery",
      "Neurology" => "Neurology",
      "Obstetrics & Gynecology" => "Obstetrics & Gynecology",
      "Ophthalmology" => "Ophthalmology",
      "Organizational Sciences & Communication" => "Organizational Sciences & Communication",
      "Orthopaedic Surgery" => "Orthopaedic Surgery",
      "Paralegal Studies" => "Paralegal Studies",
      "Pathology" => "Pathology",
      "Peace Studies" => "Peace Studies",
      "Pediatrics" => "Pediatrics",
      "Pharmacology & Physiology" => "Pharmacology & Physiology",
      "Philosophy" => "Philosophy",
      "Physical Therapy & Health Care Sciences" => "Physical Therapy & Health Care Sciences",
      "Physician Assistant Studies" => "Physician Assistant Studies",
      "Physics" => "Physics",
      "Police and Security Studies" => "Police and Security Studies",
      "Political Communication" => "Political Communication",
      "Political Communication and Governance" => "Political Communication and Governance",
      "Political Management" => "Political Management",
      "Political Science" => "Political Science",
      "Prevention & Community Health" => "Prevention & Community Health",
      "Professional Psychology" => "Professional Psychology",
      "Psychiatry & Behavioral Sciences" => "Psychiatry & Behavioral Sciences",
      "Psychology" => "Psychology",
      "Public Leadership" => "Public Leadership",
      "Public Policy & Public Administration" => "Public Policy & Public Administration",
      "Publishing" => "Publishing",
      "Radiology" => "Radiology",
      "Real Estate & Urban Development" => "Real Estate & Urban Development",
      "Religion" => "Religion",
      "Romance, German & Slavic Languages & Literatures" => "Romance, German & Slavic Languages & Literatures",
      "School of Media & Public Affairs" => "School of Media & Public Affairs",
      "School of Nursing" => "School of Nursing",
      "Security and Safety Leadership" => "Security and Safety Leadership",
      "Security Policy Studies" => "Security Policy Studies",
      "Sociology" => "Sociology",
      "Special Education & Disability Studies" => "Special Education & Disability Studies",
      "Speech & Hearing Sciences" => "Speech & Hearing Sciences",
      "Statistics" => "Statistics",
      "Strategic Management & Public Policy" => "Strategic Management & Public Policy",
      "Strategic Public Relations" => "Strategic Public Relations",
      "Surgery" => "Surgery",
      "Sustainable Urban Planning" => "Sustainable Urban Planning",
      "Theatre & Dance" => "Theatre & Dance",
      "Undergraduate Public Health" => "Undergraduate Public Health",
      "University Writing" => "University Writing",
      "Urology" => "Urology",
      "Women's Studies" => "Women's Studies",
    }
  end
end
