menubar: false
toolbar1: styleselect | bold italic | link image | undo redo
toolbar2: table | fullscreen | uploadimage | code | forecolor | backcolor
plugins:
  - table
  - fullscreen
  - uploadimage
  - code
  - textcolor
